apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
  namespace: default
  labels:
    app: nextjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: mommakara026/test-build # Replace with your Docker image
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
