---
- name: Deploy Kubernetes resources with arguments
  hosts: myhosts
  tasks:
    - name: Debug app_name and image_name
     debug:
       msg: "app_name: {{ app_name }}, image_name: {{ image_name }}"
    - name: Run deploy-pod.sh with application name and image name parameters
      shell: "/home/minikubeuser/deploy-pod.sh {{ app_name }} {{ image_name }}"
      environment:
        app_name: "{{ app_name }}"
        image_name: "{{ image_name }}"
      args:
        chdir: "/home/minikubeuser"
